import time

def test_facebook(page):
    page.goto("https://www.facebook.com/register")
    page.get_by_label("Имя").click()
    page.get_by_label("Имя").fill("Даниэл")
    page.get_by_label("Фамилия").click()
    page.get_by_label("Фамилия").press("CapsLock")
    page.get_by_label("Фамилия").fill("К")
    page.get_by_label("Фамилия").press("CapsLock")
    page.get_by_label("Фамилия").fill("Каныбеков")
    page.get_by_label("Номер мобильного телефона или эл. адрес").click()
    page.get_by_label("Номер мобильного телефона или эл. адрес").fill("kanybekovdaniel6@gmail.com")
    page.wait_for_selector("label:has-text[\"Повторно введите ваш эл. адрес\"]")
    page.get_by_label("Повторно введите ваш эл. адрес").click()
    page.get_by_label("Повторно введите ваш эл. адрес").fill("kanybekovdaniel6@gmail.com")
    page.get_by_label("Новый пароль").click()
    page.get_by_label("Новый пароль").fill("*******")
    page.get_by_label("Год").select_option("2004")
    page.get_by_label("Месяц").select_option("4")
    page.get_by_label("День").select_option("23")
    page.get_by_label("Мужчина").check()
    page.get_by_role("button", name="Регистрация").click()
    page.goto("https://www.facebook.com/")